# Hello World iOS Widget

This is a simple iOS application containing a WidgetKit extension that displays "Hello World". It supports all iOS widget sizes and is configured to be built automatically via GitHub Actions.

## How to Install (No Developer Account Required)

Apple allows anyone with a free Apple ID to side-load apps onto their own iPhone. 

Since you are likely developing on **Windows**, the easiest way to install this app is by using a tool like [Sideloadly](https://sideloadly.io/) or [AltStore](https://altstore.io/) alongside the `.ipa` file generated by GitHub Actions.

### Method 1: Installing from Windows (Sideloadly)

1. **Get the IPA file:**
   - Create a new tag and release to trigger the GitHub Action. If you have the GitHub CLI (`gh`) installed, you can run:
     ```bash
     gh release create v1.0.0 --title "v1.0.0" --generate-notes
     ```
     *(Alternatively, create a Release manually from the GitHub website).*
   - Go to your repository's **Releases** tab.
   - Download the `HelloWorldApp.ipa` file attached to the latest release (this will appear a few minutes after the action finishes).
2. **Install Sideloadly:**
   - Download and install [Sideloadly](https://sideloadly.io/) on your Windows PC.
   - **Important**: Make sure you have iTunes & iCloud installed directly from Apple's website (do *not* use the Microsoft Store versions).
3. **Enable Developer Mode (iOS 16+):**
   - On your iPhone, go to **Settings > Privacy & Security**.
   - Scroll down to **Developer Mode** and enable it (requires a restart).
4. **Side-load the App:**
   - Plug your iPhone into your PC.
   - Open Sideloadly.
   - Drag and drop `HelloWorldApp.ipa` into the Sideloadly window.
   - Enter your free Apple ID email.
   - Click **Start** (it may prompt you for your Apple ID password, which is sent securely to Apple to sign the app).
5. **Trust the Developer:**
   - Once installed, go to **Settings > General > VPN & Device Management** on your iPhone.
   - Tap your Apple ID under "Developer App" and click **Trust**.
   - You can now open the app and add the Widget to your home screen!

#### Keeping the App Active (Wi-Fi Auto Refresh)
Apps signed with a free Apple ID expire every 7 days. Instead of plugging your phone in every week, you can configure Sideloadly to refresh it automatically over Wi-Fi:
1. Connect your iPhone via USB and open iTunes.
2. Go to your Connected Device > Summary > Options.
3. Enable **"Sync with this iDevice over Wi-Fi"**, click Sync, and you can unplug your phone.
4. In Sideloadly, ensure the **automatic refresh** option is enabled when sideloading. As long as your PC and iPhone are on the same Wi-Fi network, Sideloadly Daemon will automatically refresh the app before it expires!

### Method 2: Installing from a Mac (Xcode)

If you have access to a Mac:

1. Open Terminal and install XcodeGen: `brew install xcodegen`
2. Clone this repository and navigate to it in Terminal.
3. Run `xcodegen generate` to create `HelloWorldApp.xcodeproj`.
4. Open `HelloWorldApp.xcodeproj` in Xcode.
5. In the project navigator, click `HelloWorldApp`.
6. Go to the **Signing & Capabilities** tab.
7. Select **Automatically manage signing**.
8. From the Team dropdown, select your Personal Team (add your Apple ID in Xcode Preferences if you haven't already).
9. Do the same for the `HelloWorldWidget` target.
10. Ensure **Developer Mode** is enabled on your iPhone (Settings > Privacy & Security).
11. Plug in your iPhone, select it as the run destination, and click **Run** (Play button).
